# Generated by Django 6.0.5 on 2026-06-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=40)),
                ('type', models.CharField(choices=[('Classic', 'Classic'), ('Executive', 'Executive'), ('VIP', 'VIP')], default='Classic', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=50)),
                ('estimated_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fare', models.IntegerField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Boarding', 'Boarding'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=30)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tickets.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tickets.route')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=150)),
                ('passenger_phone', models.CharField(max_length=50)),
                ('selected_seats', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money'), ('card', 'Credit/Debit Card')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('booking_ref', models.CharField(max_length=50, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tickets.customeruser')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.trip')),
            ],
        ),
    ]
